jobs:
  build:
    if: (github.repository == 'apache/shenyu')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ matrix.os == 'windows-latest'}}
      name: Support longpaths
      run: git config --system core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: .github/filters.yml
        list-files: json
    - continue-on-error: true
      id: restore-maven-cache
      if: steps.filter.outputs.changed == 'true'
      name: Restore ShenYu Maven Repos
      uses: actions/cache/restore@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Build with Maven
      run: ./mvnw -B clean test -Prelease
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      uses: codecov/codecov-action@v1
      with:
        token: 2760af6a-3405-4882-9e61-04c5176fecfa
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true' && steps.restore-maven-cache.outputs.cache-hit
        != 'true'
      name: Save ShenYu Maven Repos
      uses: actions/cache/save@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
    strategy:
      matrix:
        include:
        - java: 12
          os: ubuntu-latest
        - java: 13
          os: ubuntu-latest
        - java: 14
          os: ubuntu-latest
        - java: 15
          os: ubuntu-latest
        - java: 16
          os: ubuntu-latest
        - java: 17
          os: ubuntu-latest
        - java: 18
          os: ubuntu-latest
        - java: 19
          os: ubuntu-latest
        - java: 20
          os: ubuntu-latest
        - java: 21
          os: ubuntu-latest
        java:
        - 8
        - 11
        - 17
        os:
        - ubuntu-latest
        - windows-latest
  check-license-header:
    name: check-license-header
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Check License Header
      uses: apache/skywalking-eyes@9bd5feb86b5817aa6072b008f9866a2c3bbc8587
    timeout-minutes: 10
  requirement:
    if: always()
    name: build
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checking job status
      run: '[[ "${{ needs.build.result }}" == "success" ]] || exit -1

        '
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
