env:
  REPOSITORY: ${{ github.repository }}
  TAG: ${{ github.ref_name }}
jobs:
  dockerhub:
    if: (github.repository == 'apache/shenyu')
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USER }}
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - continue-on-error: true
      id: restore-maven-cache
      name: Restore ShenYu Maven Repos
      uses: actions/cache/restore@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B clean -Prelease -Dmaven.javadoc.skip=true -B -Drat.skip=true
        -Djacoco.skip=true -DskipITs -DskipTests package
    - continue-on-error: true
      name: Build and push (admin) (dockerhub)
      uses: docker/build-push-action@v3
      with:
        build-args: APP_NAME=apache-shenyu-*-admin-bin
        context: ./shenyu-dist/shenyu-admin-dist
        file: ./shenyu-dist/shenyu-admin-dist/docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: 'apache/shenyu-admin:latest

          apache/shenyu-admin:${{ env.TAG }}

          '
    - continue-on-error: true
      name: Build and push (bootstrap) (dockerhub)
      uses: docker/build-push-action@v3
      with:
        build-args: APP_NAME=apache-shenyu-*-bootstrap-bin
        context: ./shenyu-dist/shenyu-bootstrap-dist
        file: ./shenyu-dist/shenyu-bootstrap-dist/docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: 'apache/shenyu-bootstrap:latest

          apache/shenyu-bootstrap:${{ env.TAG }}

          '
name: docker-publish-dockerhub
on:
  repository_dispatch:
    types: trigger-ga___docker-publish-dockerhub.yml
