jobs:
  build:
    if: github.repository == 'apache/shenyu'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: .github/filters.yml
        list-files: json
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Clean Space
      run: 'sudo rm -rf /usr/share/dotnet

        sudo rm -rf /opt/ghc

        sudo rm -rf "/usr/local/share/boost"

        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

        '
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Cache Maven Repos
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Install k8s
      run: 'go install sigs.k8s.io/kind@v0.14.0

        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.24.14/bin/linux/amd64/kubectl
        && sudo install kubectl /usr/local/bin/kubectl

        kind create cluster --image=kindest/node:v1.21.1 --config=./shenyu-integrated-test/${{
        matrix.case }}/deploy/kind-config.yaml

        '
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Cache Maven Repos
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Build with Maven
      run: ./mvnw -B clean install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Build integrated tests
      run: ./mvnw -B clean install -Pit -DskipTests -am -f ./shenyu-integrated-test/pom.xml
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Build examples
      run: ./mvnw -B clean install -Pexample -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
        -am -f ./shenyu-examples/pom.xml
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Build k8s Cluster
      run: bash ./shenyu-integrated-test/${{ matrix.case }}/script/build_k8s_cluster.sh
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Wait for k8s Cluster Start up
      run: 'bash ./shenyu-integrated-test/${{ matrix.case }}/script/healthcheck.sh

        '
      timeout-minutes: 15
    - continue-on-error: true
      id: test
      if: steps.filter.outputs.changed == 'true'
      name: Run test
      run: ./mvnw test -Pit -f ./shenyu-integrated-test/${{ matrix.case }}/pom.xml
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Cluster Test after Healthcheck
      run: "kubectl get all\nkubectl get all -n shenyu-ingress\nkubectl get events\
        \ --all-namespaces\nkubectl logs -l app=shenyu-ingress-controller -n shenyu-ingress\
        \ --tail=-1\nif [[ ${{steps.test.outcome}} == \"failure\" ]]; then\n  echo\
        \ \"Test Failed\"\n  exit 1\nelse\n  echo \"Test Successful\"\n  exit 0\n\
        fi\n"
    strategy:
      matrix:
        case:
        - shenyu-integrated-test-k8s-ingress-http
        - shenyu-integrated-test-k8s-ingress-apache-dubbo
        - shenyu-integrated-test-k8s-ingress-motan
        - shenyu-integrated-test-k8s-ingress-spring-cloud
        - shenyu-integrated-test-k8s-ingress-websocket
        - shenyu-integrated-test-k8s-ingress-grpc
        - shenyu-integrated-test-k8s-ingress-sofa
name: it-k8s
on:
  repository_dispatch:
    types: trigger-ga___integrated-test-k8s-ingress.yml
