jobs:
  build:
    if: (github.repository == 'apache/shenyu')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      name: Free disk space
      run: 'df --human-readable

        sudo apt clean

        docker rmi $(docker image ls --all --quiet)

        rm --recursive --force "$AGENT_TOOLSDIRECTORY"

        df --human-readable

        '
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: .github/filters.yml
        list-files: json
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Restore ShenYu Maven Repos
      uses: actions/cache/restore@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Build with Maven
      run: ./mvnw -B clean install -Prelease,docker -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Build examples
      run: ./mvnw -B clean install -Pexample -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
        -am -f ./shenyu-examples/pom.xml
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Build integrated tests
      run: ./mvnw -B clean install -Pit -DskipTests -f ./shenyu-integrated-test/pom.xml
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Start docker compose
      run: docker compose -f ./shenyu-integrated-test/${{ matrix.case }}/docker-compose.yml
        up -d
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Wait for docker compose start up completely
      run: bash ./shenyu-integrated-test/${{ matrix.case }}/script/healthcheck.sh
    - continue-on-error: true
      name: Disk space info
      run: 'df --human-readable

        '
    - continue-on-error: true
      id: test
      if: steps.filter.outputs.changed == 'true'
      name: Run test
      run: ./mvnw test -Pit -f ./shenyu-integrated-test/${{ matrix.case }}/pom.xml
    - continue-on-error: true
      if: steps.filter.outputs.changed == 'true'
      name: Check test result
      run: "docker compose -f ./shenyu-integrated-test/${{ matrix.case }}/docker-compose.yml\
        \ logs --tail=\"all\"\nif [[ ${{steps.test.outcome}} == \"failure\" ]]; then\n\
        \  echo \"Test Failed\"\n  exit 1\nelse\n  echo \"Test Successful\"\n  exit\
        \ 0\nfi"
    strategy:
      matrix:
        case:
        - shenyu-integrated-test-apache-dubbo
        - shenyu-integrated-test-grpc
        - shenyu-integrated-test-http
        - shenyu-integrated-test-https
        - shenyu-integrated-test-motan
        - shenyu-integrated-test-spring-cloud
        - shenyu-integrated-test-sofa
        - shenyu-integrated-test-websocket
        - shenyu-integrated-test-rewrite
        - shenyu-integrated-test-combination
        - shenyu-integrated-test-sdk-apache-dubbo
        - shenyu-integrated-test-sdk-http
name: it
on:
  repository_dispatch:
    types: trigger-ga___integrated-test.yml
